spring:
  application:
    name: task-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker
    username: task_tracker_db_client
    password: task_tracker_db_client
  liquibase:
    enabled: true
    change-log: classpath:scripts/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/task_tracker
    user: task_tracker_db_admin
    password: task_tracker_db_admin
    liquibase-schema: "liquibase"
    default-schema: "task_tracker"
  jackson:
    default-property-inclusion: non_null

  security:
    user:
      name: admin
      password: admin

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  boot.admin.client:
    url: http://localhost:8081
    username: admin
    password: admin
    instance:
      metadata:
        user.name: ${spring.security.user.name}
        user.password: ${spring.security.user.password}

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always
  info.env.enabled: true

task-tracker:
  page-default-size: 20
  page-max-size: 40